### ISSUE TITLE
Is it possible to use AirPlayRoutePickerView() with other video player

### ISSUE THREAD

**Issue by expertdevs** [MrJai/flutter_to_airplay#5]
Hello, 
Thanks to make this plugin I really need this. But I want to know Is it possible to use AirPlayRoutePickerView() with other video player (like [flick_video_player](https://pub.dev/packages/flick_video_player)) or if possible please add video controllers and screen orientation functionality.

**Comment by MrJai** [comment]
Hi, theoretically it should be, as it is an independent widget that can be integrated anywhere, but it still needs to be tested in such cases. Do let me know if it works for you or not and I will be available to improve it if there is an issue.

Regarding further support of video controllers and orientation functionality, please give me time, I work on these over the weekends only, but I will try to check it out during the week as well. In the meantime, if you want to contribute, please feel free to open a PR and I will review that.

Thank you for your comment.

**Comment by expertdevs** [comment]
I tried to integrate it independently and it worked 1st time but 2nd time when i played my video app app crashed with any logs.

**Comment by MrJai** [comment]
Can you share the logs or the PR, so that I can review and fix it?
It will be difficult to fix without reproducing.

**Comment by expertdevs** [comment]
I tried with xCode and got this 

`Fatal error: Unexpectedly found nil while unwrapping an Optional value: file /path/flutter_sdk/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_to_airplay-1.0.2/ios/Classes/FlutterAVPlayer.swift, line 26`

**Comment by MrJai** [comment]
Okay, let me fix it.
Can you share the widget code as well? how you are creating FlutterAVPlayer widget.

**Comment by expertdevs** [comment]
I used [flick_video_player](https://pub.dev/packages/flick_video_player) because I need to play video in landscape mode

**Comment by MrJai** [comment]
I just pushed a fix to the master branch. I will submit a new version to pub.dev in a few minutes.

**Comment by JigarKotak7** [comment]
Any update on above? As I am still facing the same issue.

Fatal error: Unexpectedly found nil while unwrapping an Optional value

**Comment by JigarKotak7** [comment]
I have found a workaround but you can find a proper solution to it, I was going through the code and using breakpoints realized that the first time I build AirPlayRoutePickerView() Widget it builds it properly and when I try to build it second time it was trying to build FlutterAVPlayer() Widget instead and it was null so the app was crashing. So in the below file you see 
if viewId == 1 it build the AirPlayRoutePickerView() else it would build FlutterAVPlayer() Widget and when I try to load the page second time the viewId is incremented, for now I have changed it to if viewId >= 1 and it works for my purpose but you can implement a proper fix for it.

Thank you
Jigar Kotak

//
//  SharePlatformViewFactory.swift
//  flutter_to_airplay
//
//  Created by Junaid Rehmat on 22/08/2020.
//
import Foundation
import Flutter

class SharePlatformViewFactory: NSObject, FlutterPlatformViewFactory {
    var _messenger : FlutterBinaryMessenger
    
    init(messenger: FlutterBinaryMessenger & NSObjectProtocol) {
        _messenger = messenger
    }
    
    func create(withFrame frame: CGRect, viewIdentifier viewId: Int64, arguments args: Any?) -> FlutterPlatformView {
        if viewId == 1 {
            let pickerView = FlutterRoutePickerView(frame: frame, viewIdentifier: viewId, arguments: args as! Dictionary<String, Any>, binaryMessenger: _messenger)
            return pickerView
        }
        else
        {
            let pickerView = FlutterAVPlayer(frame: frame, viewIdentifier: viewId, arguments: args as! Dictionary<String, Any>, binaryMessenger: _messenger)
            return pickerView
        }
    }
    
    func createArgsCodec() -> FlutterMessageCodec & NSObjectProtocol {
        return FlutterStandardMessageCodec.sharedInstance()
    }
}

**Comment by MrJai** [comment]
Thank you @expertdevs and @JigarKotak7. I have published version 1.0.4 and that will fix all of the crash issues. Please feel free to comment if you notice any further crashes. I will try to be more responsive now.
